DELETE FROM Utente WHERE idUtente != 0;
insert into Utente (idUtente, email, password, username) values (1, 'cbrewitt0@vistaprint.com', 'p2yGSP', 'rnassi0');
insert into Utente (idUtente, email, password, username) values (2, 'sgladbeck1@cnn.com', 'RZTtr7EwRhu', 'hbuddle1');
insert into Utente (idUtente, email, password, username) values (3, 'drugge2@irs.gov', '6SvonQ6QLetd', 'ghoogendorp2');
insert into Utente (idUtente, email, password, username) values (4, 'gsedgeworth3@linkedin.com', 'vbBn3kan', 'ataig3');
insert into Utente (idUtente, email, password, username) values (5, 'ejago4@xing.com', 'QN2IwQw', 'tandryunin4');
insert into Utente (idUtente, email, password, username) values (6, 'locannovane5@thetimes.co.uk', '4HSUu0', 'mgwillim5');
insert into Utente (idUtente, email, password, username) values (7, 'psexcey6@webeden.co.uk', 'dAls2XI', 'kskase6');
insert into Utente (idUtente, email, password, username) values (8, 'pdanielut7@devhub.com', 'GZ4haOi', 'dsaffe7');
insert into Utente (idUtente, email, password, username) values (9, 'lmacturlough8@nydailynews.com', 'EfHSzTWO5', 'egrigorini8');
insert into Utente (idUtente, email, password, username) values (10, 'vbater9@cbc.ca', 'gcekEFu0Nr', 'wwilshire9');
insert into Utente (idUtente, email, password, username) values (11, 'jmeesona@arstechnica.com', '1cchNVRh', 'fsandcrofta');
insert into Utente (idUtente, email, password, username) values (12, 'bmoteb@mapy.cz', 'pkfRpYSit', 'tbeswickb');
insert into Utente (idUtente, email, password, username) values (13, 'fmeec@hud.gov', 'yU2aslq', 'imottoc');
insert into Utente (idUtente, email, password, username) values (14, 'kpattend@microsoft.com', 'E02TYcA', 'dragsdaled');
insert into Utente (idUtente, email, password, username) values (15, 'gheisse@blinklist.com', 'PlShmeJd3', 'flewsone');
insert into Utente (idUtente, email, password, username) values (16, 'lmclayf@shinystat.com', 'dEhUtCVWD', 'mhunnawillf');
insert into Utente (idUtente, email, password, username) values (17, 'dhenrysong@amazon.co.jp', '8lfImR', 'bcowopeg');
insert into Utente (idUtente, email, password, username) values (18, 'rtanslieh@cafepress.com', 'wZKac6K4', 'haskewh');
insert into Utente (idUtente, email, password, username) values (19, 'lbrezlawi@ehow.com', 'l7BTFcBSLw', 'ccourtonnei');
insert into Utente (idUtente, email, password, username) values (20, 'lleghornj@studiopress.com', 'vGlgxst3oj1n', 'wsymcockj');
insert into Utente (idUtente, email, password, username) values ('21','admin21@adm','PWWD21admin','u21Admin');
insert into Utente (idUtente, email, password, username) values ('22','admin22@adm','PWWD22admin','u22Admin');
insert into Utente (idUtente, email, password, username) values ('23','vend23@v','PWWD23vend','u23vend');
insert into Utente (idUtente, email, password, username) values ('24','vend24@v','PWWD24vend','u24vend');
insert into Utente (idUtente, email, password, username) values ('25','compr25@c','PWWD25compr','u25compr');
insert into Utente (idUtente, email, password, username) values ('26','compr26@c','PWWD26compr','u26compr');